language: scala

scala:
  - 2.12.9

jdk:
  - openjdk8

sudo: false

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
    - stage: test
      script: sbt ++$TRAVIS_SCALA_VERSION test
    # run release only if previous stages passed
    - stage: release
      script: sbt ci-release || sbt sonatypeReleaseAll
