addSbtPlugin("org.scalameta"             % "sbt-scalafmt"   % "2.4.0")
addSbtPlugin("com.github.gseitz"         % "sbt-release"    % "1.0.13")
addSbtPlugin("com.geirsson"              % "sbt-ci-release" % "1.5.3")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.11")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"   % "0.9.15-2")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"  % "1.6.1")
