name: Coverage report

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compile
      run: sbt coverage compile
    - name: Run tests
      run: sbt test
    - name: Generate coverage report
      run: sbt coverageReport
    - uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
